url: http://blog.mgechev.com/
root: /
title: Minko Gechev's blog
name: Minko Gechev's blog
description: 1.61803399 == 42 //!!!
baseurl: ''

markdown: kramdown
permalink: pretty
github: git@github.com:mgechev/blog.mgechev.com.git
