# Site settings
title: Minko Gechev's blog
email: mgechev@gmail.com
description: "1.618033988 == 42!!!"
baseurl: ""
url: "http://blog.mgechev.com"

# Build settings
markdown: kramdown
permalink: pretty
