url: http://blog.mgechev.com/
title: Minko Gechev's blog
name: 'Minko Gechev&#039;s blog'
description: 1.61803399 == 42 //!!!

markdown: kramdown
permalink: pretty
github: git@github.com:mgechev/blog.mgechev.com.git
